### ISSUE TITLE
באג במחיקת שלט

### ISSUE THREAD

**Issue by YehudahA** [YehudahA/UrbanDigitalWork#4]
1.  תיקון באג בעת מחיקת שלט PIS.
2. מחיקה תשנה את המזהה של השלט, כדי שניתן יהיה להקים שלט חדש עם אותו מזהה

הערכת משך זמן: שעה.

**Comment by YehudahA** [comment]
DELETE https://xpis.urban-digital.co.il/api/devices/1783
   System.Net.Http.HttpRequestException: Response status code does not indicate success: 405 (Method Not Allowed).
     at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
     at UrbanView.Services.PisCtsApiClient.DeleteAsync(Int32 id) in C:\Users\User\Source\Repos\urban-view2\UrbanView\Services\PisCtsApiClient.cs:line 54
     at UrbanView.Areas.Api.Controllers.DevicesApiController.Delete(Int32 id, IPisCtsApiClient ctsApiClient) in C:\Users\User\Source\Repos\urban-view2\UrbanView\Areas\Api\Controllers\DevicesApiController.cs:line 41
     at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
     at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by YehudahA** [comment]
תוקן בשעה וחמש דקות.
נוספו עוד כמה שיפורים המתייחסים לכמה מצבים.

https://bitbucket.org/urbandigital/urban-view/commits/53fc80633cee8f295b8d05b538732d1150ad231b
